# Generated by Django 4.1.13 on 2024-02-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=150)),
                ('pdesc', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('offer', models.FloatField()),
                ('stock_count', models.IntegerField()),
                ('createdat', models.DateField(auto_now=True)),
                ('img1', models.ImageField(upload_to='products')),
                ('img2', models.ImageField(upload_to='products')),
                ('img3', models.ImageField(upload_to='products')),
                ('img4', models.ImageField(upload_to='products')),
                ('img5', models.ImageField(blank=True, null=True, upload_to='products')),
                ('material', models.CharField(max_length=50)),
                ('warranty', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Products',
            },
        ),
    ]
