# Generated by Django 4.1.13 on 2024-02-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cancelitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='null', max_length=150),
            preserve_default=False,
        ),
    ]
