# Generated by Django 4.1.13 on 2024-03-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_order_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mob', models.IntegerField()),
                ('reason', models.TextField()),
                ('img', models.ImageField(upload_to='contactus')),
                ('message', models.TextField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
