# Generated by Django 4.1.13 on 2024-03-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_contactus_mob'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50, verbose_name='Place')),
                ('review', models.TextField()),
                ('img', models.ImageField(upload_to='review', verbose_name='Image')),
                ('rating', models.FloatField()),
            ],
        ),
    ]
