# Generated by Django 4.1.13 on 2024-03-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_reviewsite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsite',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='review', verbose_name='Image'),
        ),
    ]
